{
  try {
    TestUser user1=null;
    TestUser user2=null;
    TestOne t1=null;
    Class type=TestOne.class;
    final App superUserApp=StructrApp.getInstance();
    try (final Tx tx=app.tx()){
      List<TestUser> users=createTestNodes(TestUser.class,2);
      user1=(TestUser)users.get(0);
      user1.setProperty(AbstractNode.name,"user1");
      user2=(TestUser)users.get(1);
      user2.setProperty(AbstractNode.name,"user2");
      t1=createTestNode(TestOne.class);
      t1.setProperty(AbstractNode.owner,user1);
      tx.success();
    }
 catch (    FrameworkException ex) {
      logger.error(ex.toString());
    }
    try (final Tx tx=app.tx()){
      assertEquals(user1,t1.getProperty(AbstractNode.owner));
      final App user1App=StructrApp.getInstance(SecurityContext.getInstance(user1,AccessMode.Backend));
      assertEquals(t1,user1App.nodeQuery(type).getFirst());
    }
     try (final Tx tx=app.tx()){
      t1.setProperty(AbstractNode.owner,user2);
      tx.success();
    }
 catch (    FrameworkException ex) {
      logger.error(ex.toString());
    }
    try (final Tx tx=app.tx()){
      final App user2App=StructrApp.getInstance(SecurityContext.getInstance(user2,AccessMode.Backend));
      assertEquals(t1,user2App.nodeQuery(type).getFirst());
      assertEquals(user2,t1.getProperty(AbstractNode.owner));
    }
   }
 catch (  FrameworkException ex) {
    logger.error(ex.toString());
    fail("Unexpected exception");
  }
}
